name: work_timer
description: Private local work timer for Android
publish_to: "none"
version: 1.0.3+4

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.1
  path: ^1.9.0
  http: ^1.2.2
  crypto: ^3.0.3
  package_info_plus: ^8.0.2
  path_provider: ^2.1.4
  open_filex: ^4.5.0
  flutter_secure_storage: ^9.2.2
  pdf: ^3.11.1
  printing: ^5.13.4

flutter:
  uses-material-design: true
